services:
  backend:
    build: ./Atmo-backend
    container_name: atmo-backend
    ports:
      - "3030:3030"
    networks:
      - atmo-net

  frontend:
    build: ./Atmo-frontend
    container_name: atmo-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - atmo-net
    environment:
      - VITE_API_URL=http://backend:3030/api/

networks:
  atmo-net:
    driver: bridge
